In [9]:
import pandas as pd
from quickbooks_sync import get_qb_client
from quickbooks.objects.account import Account

In [16]:
df = pd.read_csv("data/tide_transactions.csv")
df.head()

,Date,Bank description,Spent,Received,From/To,Match/Categorise
0,12/03/2026,Hope 7 Ward Royal Parade Alma Road,£6.10,NaN,NaN,NaN
1,12/03/2026,Medium Annual Pmb San Francisco 548 Market Street,£37.34,NaN,NaN,Subscriptions
2,12/03/2026,Connected,£1.26,NaN,NaN,NaN
3,11/03/2026,George Inn,£5.40,NaN,NaN,NaN
4,11/03/2026,Ringgo,£4.70,NaN,NaN,NaN

In [6]:
summary = df.groupby('Bank description').agg(
    count=('Bank description', 'size'),
    most_common_category=('Match/Categorise', lambda x: x.mode()[0] if not x.mode().empty else None)
).sort_values('count', ascending=False)

summary.head()

                           count most_common_category
Bank description
Dwyer R G Ref Tide            65                  NaN
Eat Thai                      57                  NaN
Waitrose                      46                  NaN
Liberto Lounge Unit C Gem     42                  NaN
Wickes                        42                  NaN

In [7]:
summary.to_excel('data/bank_transaction_summary.xlsx')

In [15]:
accounts = Account.all(qb=client)

account_info = pd.DataFrame([
    {
        'Name': acc.Name,
        'SubType': acc.AccountSubType,
        'Type': acc.AccountType,
        'Classification': acc.Classification,
    }
    for acc in accounts
])

account_info.head()

,Name,SubType,Type,Classification
0,Accruals,CurrentLiabilities,Other Current Liability,Liability
1,Advertising,AdvertisingPromotional,Expense,Expense
2,Bad debt provision,AllowanceForBadDebts,Other Current Asset,Asset
3,Bank charges,FinanceCosts,Expense,Expense
4,Bank interest - received,InterestEarned,Other Income,Revenue

In [18]:
account_info.to_excel('data/accounts.xlsx')